name: 'Issue chat'
description: 'Issue responder'
branding:
  icon: 'bookmark'
  color: 'blue'
inputs:
  token:
    description: 'Github_token'
    required: true
runs:
  using: node12
  main: 'lib/index.js'
