name: Chat

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]

jobs:
  chat:
    name: Link Response
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Octokit dependency
        run: npm install @octokit/rest

      - name: Run Link Shortener Script
        run: node js/ref.js
        env:
          INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
